version: "2"
services:
  mediaservice:
    image: mediaservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - "SPRING_PROFILES_ACTIVE=prod,swagger"
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - "EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://mediaservice-postgresql:5432/MediaService"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://129.69.217.173:9080/auth/realms/jhipster"
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
    restart: always
    networks:
      - it-rex
      - default

  mediaservice-postgresql:
    image: "postgres:12.3"
    restart: always
    environment:
      - POSTGRES_USER=MediaService
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default

  minio:
    image: "minio/minio"
    restart: always
    volumes:
      - "/srv/minio/data:/data"
    ports:
      - "8087:8087"
    environment:
      MINIO_ACCESS_KEY: minio_itrex
      MINIO_SECRET_KEY: minio_itrex_secret
    command: server --address ":8087" /data

networks:
  it-rex:
    external: true
